import Navigation from "@/components/Navigation";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Waves, Wind, Beaker, Fish, Mountain, Thermometer } from "lucide-react";

const InsideOcean = () => {
  const topics = [
    {
      id: "currents",
      title: "Ocean Currents",
      icon: Wind,
      color: "bg-gradient-ocean",
      content: {
        title: "Surface & Deep Ocean Circulation",
        description: "Ocean currents are driven by winds, density differences, and Earth's rotation—transporting heat, nutrients, and organisms around the globe.",
        sections: [
          {
            title: "Surface Gyres",
            content: "Large circular current systems in ocean basins driven by prevailing winds and the Coriolis Effect. Five major gyres: North Atlantic, South Atlantic, North Pacific, South Pacific, and Indian Ocean. Flow clockwise in Northern Hemisphere, counterclockwise in Southern Hemisphere.",
            facts: ["Driven by trade winds and westerlies", "Western boundary currents are fastest", "Eastern boundary currents bring cold water"]
          },
          {
            title: "Gulf Stream",
            content: "Powerful western boundary current flowing from Gulf of Mexico along US east coast. Transports warm water northward at 100 times the flow of Amazon River. Moderates European climate by bringing tropical warmth to higher latitudes.",
            facts: ["Speed up to 2 m/s (7 km/hr)", "Transports 100 Sverdrups (1 Sv = 10⁶ m³/s)", "Water temperature 25-28°C"]
          },
          {
            title: "Upwelling & Downwelling",
            content: "Upwelling brings cold, nutrient-rich deep water to surface, supporting high productivity. Occurs along coasts where winds push surface water offshore. Downwelling sinks surface water, bringing oxygen to depth. Both essential for nutrient cycling.",
            facts: ["Coastal upwelling driven by Ekman transport", "Peru upwelling supports major fisheries", "Equatorial upwelling from trade winds"]
          },
          {
            title: "Thermohaline Circulation",
            content: "Deep ocean circulation driven by density differences from temperature (thermo) and salinity (haline). Cold, salty water sinks at poles, flows along seafloor, and rises at lower latitudes. Complete cycle takes ~1000 years. Also called the 'global conveyor belt.'",
            facts: ["Forms in North Atlantic and Antarctica", "Moves slowly: ~10-20 km/year", "Distributes heat globally"]
          }
        ]
      }
    },
    {
      id: "waves",
      title: "Waves",
      icon: Waves,
      color: "bg-gradient-wave",
      content: {
        title: "Wave Basics & Behavior",
        description: "Waves transfer energy across ocean basins, generated by wind friction on the water surface.",
        sections: [
          {
            title: "Wave Formation",
            content: "Wind-driven waves created by friction between wind and water. Wave size depends on: wind speed, duration of wind, and fetch (distance over open water). Larger waves need stronger winds, longer duration, and greater fetch.",
            facts: ["Energy travels, water stays in place", "Orbital motion below surface", "Deep water: depth > ½ wavelength"]
          },
          {
            title: "Waves at Sea vs. Shore",
            content: "Deep water waves: circular orbital motion, speed depends on wavelength. Shallow water waves: elliptical orbits, speed depends on depth. When depth < ½ wavelength, waves 'feel' bottom, slow down, wavelength decreases, height increases, eventually break.",
            facts: ["Wave speed = wavelength/period", "Refraction bends waves toward shore", "Breaking occurs when height > 1/7 wavelength"]
          },
          {
            title: "Tsunamis",
            content: "Shallow water waves generated by earthquakes, landslides, or volcanic eruptions displacing water column. Very long wavelength (100-200 km), low height in open ocean (<1m), extremely fast (700-800 km/hr). Slow and grow tall near shore.",
            facts: ["Speed in deep water: √(gd)", "Can cross Pacific in < 24 hours", "2004 Indian Ocean killed 230,000+"]
          }
        ]
      }
    },
    {
      id: "tides",
      title: "Tides",
      icon: Thermometer,
      color: "bg-gradient-coral",
      content: {
        title: "Tidal Forces & Patterns",
        description: "Tides result from gravitational pull of the Moon and Sun creating bulges in Earth's ocean water.",
        sections: [
          {
            title: "Tidal Forces",
            content: "Moon's gravity pulls water creating tidal bulge facing Moon. Centrifugal force creates bulge on opposite side. Sun also creates tides (45% as strong as Moon). Spring tides when Sun/Moon align, neap tides when perpendicular.",
            facts: ["Two high tides per day (usually)", "Spring tides: highest range", "Neap tides: smallest range"]
          },
          {
            title: "Tidal Classifications",
            content: "Diurnal: one high and one low tide per day. Semidiurnal: two high and two low tides of equal height per day. Mixed: two high and two low tides of unequal height per day. Pattern depends on basin shape and latitude.",
            facts: ["US East Coast: semidiurnal", "Gulf of Mexico: diurnal", "US West Coast: mixed"]
          }
        ]
      }
    },
    {
      id: "properties",
      title: "Physical Properties",
      icon: Thermometer,
      color: "bg-gradient-depth",
      content: {
        title: "Temperature, Density & Pressure",
        description: "Physical properties of seawater vary with depth and location, creating distinct ocean layers.",
        sections: [
          {
            title: "Temperature Profiles",
            content: "Mixed layer (0-200m): warm, uniform temperature from wind mixing. Thermocline: rapid temperature decrease with depth. Deep ocean: cold, stable ~2°C. Tropical: strong thermocline. Polar: weak/no thermocline. Temperate: seasonal changes.",
            facts: ["Ocean average: 4°C", "Surface range: -2°C to 30°C", "Stable deep ocean temperature"]
          },
          {
            title: "Density & Stratification",
            content: "Density increases with lower temperature, higher salinity, and higher pressure. Pycnocline: rapid density increase with depth. Stratification prevents mixing between surface and deep water. Warmer, less dense water floats on colder, denser water.",
            facts: ["Seawater density: 1.02-1.03 g/cm³", "Temperature has greatest effect", "Stratification limits nutrient exchange"]
          },
          {
            title: "Pressure",
            content: "Hydrostatic pressure increases 1 atmosphere per 10m depth. Average ocean depth 3,800m = 381 atm pressure. Challenger Deep 11,022m = 1,103 atm. Affects gas solubility (Henry's Law) and compresses air spaces (Boyle's Law).",
            facts: ["Surface: 1 atm", "1000m: 101 atm", "Deepest point: >1000 atm"]
          }
        ]
      }
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      {/* Hero Section */}
      <section className="pt-24 pb-16 bg-gradient-wave text-white">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center">
            <Waves className="h-16 w-16 mx-auto mb-6 animate-wave" />
            <h1 className="text-5xl md:text-6xl font-bold mb-6">Ocean Currents & Circulation</h1>
            <p className="text-xl text-white/90 leading-relaxed">
              Explore how ocean water moves around the globe through currents, waves, and tides—
              the physical engine that drives Earth's climate and marine ecosystems.
            </p>
          </div>
        </div>
      </section>

      {/* Interactive Tabs */}
      <section className="py-20 px-4">
        <div className="container mx-auto max-w-6xl">
          <Tabs defaultValue="physical" className="w-full">
            <TabsList className="grid w-full grid-cols-2 md:grid-cols-4 mb-8 h-auto p-1">
              {topics.map((topic) => (
                <TabsTrigger 
                  key={topic.id} 
                  value={topic.id}
                  className="flex flex-col items-center p-4 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
                >
                  <topic.icon className="h-6 w-6 mb-2" />
                  <span className="text-xs font-medium">{topic.title}</span>
                </TabsTrigger>
              ))}
            </TabsList>

            {topics.map((topic) => (
              <TabsContent key={topic.id} value={topic.id} className="mt-8">
                <div className="text-center mb-12">
                  <div className={`inline-flex p-4 rounded-xl ${topic.color} text-white mb-6`}>
                    <topic.icon className="h-12 w-12" />
                  </div>
                  <h2 className="text-4xl font-bold mb-4 bg-gradient-ocean bg-clip-text text-transparent">
                    {topic.content.title}
                  </h2>
                  <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
                    {topic.content.description}
                  </p>
                </div>

                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
                  {topic.content.sections.map((section, index) => (
                    <Card key={section.title} className="group hover:shadow-xl transition-all duration-300 hover:-translate-y-1">
                      <div className={`h-2 ${topic.color}`} />
                      <CardHeader>
                        <CardTitle className="text-xl mb-3">{section.title}</CardTitle>
                        <CardDescription className="text-base leading-relaxed">
                          {section.content}
                        </CardDescription>
                      </CardHeader>
                      <CardContent>
                        <div className="space-y-2">
                          <h4 className="font-semibold text-sm text-muted-foreground mb-3">Key Facts:</h4>
                          {section.facts.map((fact, factIndex) => (
                            <Badge 
                              key={factIndex} 
                              variant="secondary" 
                              className="text-xs mr-2 mb-2 px-3 py-1"
                            >
                              {fact}
                            </Badge>
                          ))}
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </TabsContent>
            ))}
          </Tabs>
        </div>
      </section>

    </div>
  );
};

export default InsideOcean;